local_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 5.0
   publish_frequency: 1.0 #5.0
   static_map: false
   rolling_window: true
   width: 2.5
   height: 2.0   
   resolution: 0.025
   transform_tolerance: 0.5
