(cl:in-package htbot-msg)
(cl:export '(SPEED-VAL
          SPEED
          TRIP-VAL
          TRIP
          TIME-VAL
          TIME
          MAXSPEED-VAL
          MAXSPEED
          MINSPEED-VAL
          MINSPEED
          AVGSPEED-VAL
          AVGSPEED
          CURSPEED-VAL
          CURSPEED
          TOTALRUNTIME-VAL
          TOTALRUNTIME
          TOTALTRIPTIME-VAL
          TOTALTRIPTIME
          TOTALDOWNTIME-VAL
          TOTALDOWNTIME
          TOTALIDLETIME-VAL
          TOTALIDLETIME
          UPTIME-VAL
          UPTIME
          TOTALTRIPDIST-VAL
          TOTALTRIPDIST
          AVGVOLT-VAL
          AVGVOLT
          AVGCURR-VAL
          AVGCURR
          MAXCURR-VAL
          MAXCURR
          MINCURR-VAL
          MINCURR
          AMPHR-VAL
          AMPHR
          BATLEVEL-VAL
          BATLEVEL
          TNUMTRIP-VAL
          TNUMTRIP
          CLEAROPS-VAL
          CLEAROPS
          ESTOP-VAL
          ESTOP
          MOTORDISABLE-VAL
          MOTORDISABLE
          ALARMLOG-VAL
          ALARMLOG
          HEARTBEAT-VAL
          HEARTBEAT
))