(cl:in-package htbot-msg)
(cl:export '(CMD-VAL
          CMD
          PX-VAL
          PX
          PY-VAL
          PY
          PZ-VAL
          PZ
          PRX-VAL
          PRX
          PRY-VAL
          PRY
          PRZ-VAL
          PRZ
          PRW-VAL
          PRW
          GX-VAL
          GX
          GY-VAL
          GY
          GZ-VAL
          GZ
          GRX-VAL
          GRX
          GRY-VAL
          GRY
          GRZ-VAL
          GRZ
          GRW-VAL
          GRW
          TOL-VAL
          TOL
))