(cl:in-package htbot-msg)
(cl:export '(CMD-VAL
          CMD
          STARTIDX-VAL
          STARTIDX
          LASTIDX-VAL
          LASTIDX
          NUMGOAL-VAL
          NUMGOAL
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          RX-VAL
          RX
          RY-VAL
          RY
          RZ-VAL
          RZ
          RW-VAL
          RW
          PD-VAL
          PD
          PA-VAL
          PA
          OPT-VAL
          OPT
))