// Generated by gencpp from file videocontrol/dyna.msg
// DO NOT EDIT!


#ifndef VIDEOCONTROL_MESSAGE_DYNA_H
#define VIDEOCONTROL_MESSAGE_DYNA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace videocontrol
{
template <class ContainerAllocator>
struct dyna_
{
  typedef dyna_<ContainerAllocator> Type;

  dyna_()
    : paramid(0)
    , intValue(0)
    , doubleValue(0.0)
    , strValue()
    , boolValue(false)  {
    }
  dyna_(const ContainerAllocator& _alloc)
    : paramid(0)
    , intValue(0)
    , doubleValue(0.0)
    , strValue(_alloc)
    , boolValue(false)  {
  (void)_alloc;
    }



   typedef int8_t _paramid_type;
  _paramid_type paramid;

   typedef int32_t _intValue_type;
  _intValue_type intValue;

   typedef double _doubleValue_type;
  _doubleValue_type doubleValue;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _strValue_type;
  _strValue_type strValue;

   typedef uint8_t _boolValue_type;
  _boolValue_type boolValue;





  typedef boost::shared_ptr< ::videocontrol::dyna_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::videocontrol::dyna_<ContainerAllocator> const> ConstPtr;

}; // struct dyna_

typedef ::videocontrol::dyna_<std::allocator<void> > dyna;

typedef boost::shared_ptr< ::videocontrol::dyna > dynaPtr;
typedef boost::shared_ptr< ::videocontrol::dyna const> dynaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::videocontrol::dyna_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::videocontrol::dyna_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace videocontrol

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'videocontrol': ['/home/rac/catkin_ws/src/videocontrol/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::videocontrol::dyna_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::videocontrol::dyna_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::videocontrol::dyna_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::videocontrol::dyna_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::videocontrol::dyna_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::videocontrol::dyna_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::videocontrol::dyna_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d03e42ff56dea7eeef77a3e537361b9";
  }

  static const char* value(const ::videocontrol::dyna_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d03e42ff56dea7eULL;
  static const uint64_t static_value2 = 0xeef77a3e537361b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::videocontrol::dyna_<ContainerAllocator> >
{
  static const char* value()
  {
    return "videocontrol/dyna";
  }

  static const char* value(const ::videocontrol::dyna_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::videocontrol::dyna_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 paramid\n\
int32 intValue\n\
float64 doubleValue\n\
string strValue\n\
bool boolValue\n\
";
  }

  static const char* value(const ::videocontrol::dyna_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::videocontrol::dyna_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.paramid);
      stream.next(m.intValue);
      stream.next(m.doubleValue);
      stream.next(m.strValue);
      stream.next(m.boolValue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dyna_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::videocontrol::dyna_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::videocontrol::dyna_<ContainerAllocator>& v)
  {
    s << indent << "paramid: ";
    Printer<int8_t>::stream(s, indent + "  ", v.paramid);
    s << indent << "intValue: ";
    Printer<int32_t>::stream(s, indent + "  ", v.intValue);
    s << indent << "doubleValue: ";
    Printer<double>::stream(s, indent + "  ", v.doubleValue);
    s << indent << "strValue: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.strValue);
    s << indent << "boolValue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.boolValue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIDEOCONTROL_MESSAGE_DYNA_H
