(cl:in-package htbot-msg)
(cl:export '(SPEED-VAL
          SPEED
          TRIP-VAL
          TRIP
          TIME-VAL
          TIME
          MAXSPEED-VAL
          MAXSPEED
          MINSPEED-VAL
          MINSPEED
          AVGSPEED-VAL
          AVGSPEED
          CURSPEED-VAL
          CURSPEED
          TOTALTRIPTIME-VAL
          TOTALTRIPTIME
          TOTALTRIPDIST-VAL
          TOTALTRIPDIST
          AVGVOLT-VAL
          AVGVOLT
          AVGCURR-VAL
          AVGCURR
          MAXCURR-VAL
          MAXCURR
          MINCURR-VAL
          MINCURR
          AMPHR-VAL
          AMPHR
          BATLEVEL-VAL
          BATLEVEL
          CLEAROPS-VAL
          CLEAROPS
          ESTOP-VAL
          ESTOP
          MOTORDISABLE-VAL
          MOTORDISABLE
))