int16 cmd
int8 LP
int8 GN
int8 LPT
string gps
string lps
string pw
float32 tx
float32 ty
float32 tz
float32 rx
float32 ry
float32 rz
float32 rw
float32 prd
float32 pra
float32 psd
float32 psa
float32 prd1
float32 pra1
float32 psd1
float32 psa1
float32 align
float32 func
float32 trolley
float32 trolleydist
---
int16 status
float32 tx
float32 ty
float32 tz
float32 rx
float32 ry
float32 rz
float32 rw
float32 prd
float32 pra
float32 psd
float32 psa
float32 prd1
float32 pra1
float32 psd1
float32 psa1
int8 LP
int8 cLP
int8 nGP
int8 cGN
int8 nIQ
int8 marked
string gps
string lps
string lps1
string lps2
string lps3
string lps4
string lps5
string lps6
string lps7
string lps8
int8 marked1
int8 marked2
int8 marked3
int8 marked4
int8 marked5
int8 marked6
int8 marked7
int8 marked8
float32 align
float32 func
float32 trolley
float32 trolleydist
