// Generated by gencpp from file htbot/odom.msg
// DO NOT EDIT!


#ifndef HTBOT_MESSAGE_ODOM_H
#define HTBOT_MESSAGE_ODOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace htbot
{
template <class ContainerAllocator>
struct odom_
{
  typedef odom_<ContainerAllocator> Type;

  odom_()
    : dist(0.0)
    , angle(0.0)  {
    }
  odom_(const ContainerAllocator& _alloc)
    : dist(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _dist_type;
  _dist_type dist;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::htbot::odom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::htbot::odom_<ContainerAllocator> const> ConstPtr;

}; // struct odom_

typedef ::htbot::odom_<std::allocator<void> > odom;

typedef boost::shared_ptr< ::htbot::odom > odomPtr;
typedef boost::shared_ptr< ::htbot::odom const> odomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::htbot::odom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::htbot::odom_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace htbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'htbot': ['/home/rac/catkin_ws/src/htbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::htbot::odom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::htbot::odom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::htbot::odom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::htbot::odom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::htbot::odom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::htbot::odom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::htbot::odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c05404bebfe29b1ba1f590bcefdda9bc";
  }

  static const char* value(const ::htbot::odom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc05404bebfe29b1bULL;
  static const uint64_t static_value2 = 0xa1f590bcefdda9bcULL;
};

template<class ContainerAllocator>
struct DataType< ::htbot::odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "htbot/odom";
  }

  static const char* value(const ::htbot::odom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::htbot::odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 dist\n\
float32 angle\n\
";
  }

  static const char* value(const ::htbot::odom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::htbot::odom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dist);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct odom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::htbot::odom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::htbot::odom_<ContainerAllocator>& v)
  {
    s << indent << "dist: ";
    Printer<float>::stream(s, indent + "  ", v.dist);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HTBOT_MESSAGE_ODOM_H
