// Generated by gencpp from file htbot/robot.msg
// DO NOT EDIT!


#ifndef HTBOT_MESSAGE_ROBOT_H
#define HTBOT_MESSAGE_ROBOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace htbot
{
template <class ContainerAllocator>
struct robot_
{
  typedef robot_<ContainerAllocator> Type;

  robot_()
    : amclx(0.0)
    , amcly(0.0)
    , amcla(0.0)
    , robotposediff(0.0)
    , localisationstatus()  {
    }
  robot_(const ContainerAllocator& _alloc)
    : amclx(0.0)
    , amcly(0.0)
    , amcla(0.0)
    , robotposediff(0.0)
    , localisationstatus(_alloc)  {
  (void)_alloc;
    }



   typedef float _amclx_type;
  _amclx_type amclx;

   typedef float _amcly_type;
  _amcly_type amcly;

   typedef float _amcla_type;
  _amcla_type amcla;

   typedef float _robotposediff_type;
  _robotposediff_type robotposediff;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _localisationstatus_type;
  _localisationstatus_type localisationstatus;





  typedef boost::shared_ptr< ::htbot::robot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::htbot::robot_<ContainerAllocator> const> ConstPtr;

}; // struct robot_

typedef ::htbot::robot_<std::allocator<void> > robot;

typedef boost::shared_ptr< ::htbot::robot > robotPtr;
typedef boost::shared_ptr< ::htbot::robot const> robotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::htbot::robot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::htbot::robot_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace htbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'htbot': ['/home/rac/catkin_ws/src/htbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::htbot::robot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::htbot::robot_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::htbot::robot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::htbot::robot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::htbot::robot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::htbot::robot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::htbot::robot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9472043a148e005ed77686c11e7067c6";
  }

  static const char* value(const ::htbot::robot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9472043a148e005eULL;
  static const uint64_t static_value2 = 0xd77686c11e7067c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::htbot::robot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "htbot/robot";
  }

  static const char* value(const ::htbot::robot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::htbot::robot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 amclx\n\
float32 amcly\n\
float32 amcla\n\
float32 robotposediff\n\
string localisationstatus\n\
";
  }

  static const char* value(const ::htbot::robot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::htbot::robot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.amclx);
      stream.next(m.amcly);
      stream.next(m.amcla);
      stream.next(m.robotposediff);
      stream.next(m.localisationstatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::htbot::robot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::htbot::robot_<ContainerAllocator>& v)
  {
    s << indent << "amclx: ";
    Printer<float>::stream(s, indent + "  ", v.amclx);
    s << indent << "amcly: ";
    Printer<float>::stream(s, indent + "  ", v.amcly);
    s << indent << "amcla: ";
    Printer<float>::stream(s, indent + "  ", v.amcla);
    s << indent << "robotposediff: ";
    Printer<float>::stream(s, indent + "  ", v.robotposediff);
    s << indent << "localisationstatus: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.localisationstatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HTBOT_MESSAGE_ROBOT_H
