// Generated by gencpp from file htbot/sendgoal.msg
// DO NOT EDIT!


#ifndef HTBOT_MESSAGE_SENDGOAL_H
#define HTBOT_MESSAGE_SENDGOAL_H

#include <ros/service_traits.h>


#include <htbot/sendgoalRequest.h>
#include <htbot/sendgoalResponse.h>


namespace htbot
{

struct sendgoal
{

typedef sendgoalRequest Request;
typedef sendgoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sendgoal
} // namespace htbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::htbot::sendgoal > {
  static const char* value()
  {
    return "e870aaccbc4db5d4afb5053d631034b4";
  }

  static const char* value(const ::htbot::sendgoal&) { return value(); }
};

template<>
struct DataType< ::htbot::sendgoal > {
  static const char* value()
  {
    return "htbot/sendgoal";
  }

  static const char* value(const ::htbot::sendgoal&) { return value(); }
};


// service_traits::MD5Sum< ::htbot::sendgoalRequest> should match 
// service_traits::MD5Sum< ::htbot::sendgoal > 
template<>
struct MD5Sum< ::htbot::sendgoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::htbot::sendgoal >::value();
  }
  static const char* value(const ::htbot::sendgoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::htbot::sendgoalRequest> should match 
// service_traits::DataType< ::htbot::sendgoal > 
template<>
struct DataType< ::htbot::sendgoalRequest>
{
  static const char* value()
  {
    return DataType< ::htbot::sendgoal >::value();
  }
  static const char* value(const ::htbot::sendgoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::htbot::sendgoalResponse> should match 
// service_traits::MD5Sum< ::htbot::sendgoal > 
template<>
struct MD5Sum< ::htbot::sendgoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::htbot::sendgoal >::value();
  }
  static const char* value(const ::htbot::sendgoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::htbot::sendgoalResponse> should match 
// service_traits::DataType< ::htbot::sendgoal > 
template<>
struct DataType< ::htbot::sendgoalResponse>
{
  static const char* value()
  {
    return DataType< ::htbot::sendgoal >::value();
  }
  static const char* value(const ::htbot::sendgoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HTBOT_MESSAGE_SENDGOAL_H
