// Generated by gencpp from file htbot/srvcmd.msg
// DO NOT EDIT!


#ifndef HTBOT_MESSAGE_SRVCMD_H
#define HTBOT_MESSAGE_SRVCMD_H

#include <ros/service_traits.h>


#include <htbot/srvcmdRequest.h>
#include <htbot/srvcmdResponse.h>


namespace htbot
{

struct srvcmd
{

typedef srvcmdRequest Request;
typedef srvcmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvcmd
} // namespace htbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::htbot::srvcmd > {
  static const char* value()
  {
    return "30eadfa966628646a567b1a8c11f77b8";
  }

  static const char* value(const ::htbot::srvcmd&) { return value(); }
};

template<>
struct DataType< ::htbot::srvcmd > {
  static const char* value()
  {
    return "htbot/srvcmd";
  }

  static const char* value(const ::htbot::srvcmd&) { return value(); }
};


// service_traits::MD5Sum< ::htbot::srvcmdRequest> should match 
// service_traits::MD5Sum< ::htbot::srvcmd > 
template<>
struct MD5Sum< ::htbot::srvcmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::htbot::srvcmd >::value();
  }
  static const char* value(const ::htbot::srvcmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::htbot::srvcmdRequest> should match 
// service_traits::DataType< ::htbot::srvcmd > 
template<>
struct DataType< ::htbot::srvcmdRequest>
{
  static const char* value()
  {
    return DataType< ::htbot::srvcmd >::value();
  }
  static const char* value(const ::htbot::srvcmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::htbot::srvcmdResponse> should match 
// service_traits::MD5Sum< ::htbot::srvcmd > 
template<>
struct MD5Sum< ::htbot::srvcmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::htbot::srvcmd >::value();
  }
  static const char* value(const ::htbot::srvcmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::htbot::srvcmdResponse> should match 
// service_traits::DataType< ::htbot::srvcmd > 
template<>
struct DataType< ::htbot::srvcmdResponse>
{
  static const char* value()
  {
    return DataType< ::htbot::srvcmd >::value();
  }
  static const char* value(const ::htbot::srvcmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HTBOT_MESSAGE_SRVCMD_H
