# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from htbot/scanCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class scanCmd(genpy.Message):
  _md5sum = "009679f12681386d87811bbbbfbf00db"
  _type = "htbot/scanCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8 cmd
string file
float32 f1
float32 f2
float32 f3
int8 lp
int8 gp
int8 opt
"""
  __slots__ = ['cmd','file','f1','f2','f3','lp','gp','opt']
  _slot_types = ['int8','string','float32','float32','float32','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cmd,file,f1,f2,f3,lp,gp,opt

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(scanCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cmd is None:
        self.cmd = 0
      if self.file is None:
        self.file = ''
      if self.f1 is None:
        self.f1 = 0.
      if self.f2 is None:
        self.f2 = 0.
      if self.f3 is None:
        self.f3 = 0.
      if self.lp is None:
        self.lp = 0
      if self.gp is None:
        self.gp = 0
      if self.opt is None:
        self.opt = 0
    else:
      self.cmd = 0
      self.file = ''
      self.f1 = 0.
      self.f2 = 0.
      self.f3 = 0.
      self.lp = 0
      self.gp = 0
      self.opt = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.cmd
      buff.write(_get_struct_b().pack(_x))
      _x = self.file
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3f3b().pack(_x.f1, _x.f2, _x.f3, _x.lp, _x.gp, _x.opt))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.cmd,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.file = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.file = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.f1, _x.f2, _x.f3, _x.lp, _x.gp, _x.opt,) = _get_struct_3f3b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.cmd
      buff.write(_get_struct_b().pack(_x))
      _x = self.file
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3f3b().pack(_x.f1, _x.f2, _x.f3, _x.lp, _x.gp, _x.opt))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.cmd,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.file = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.file = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.f1, _x.f2, _x.f3, _x.lp, _x.gp, _x.opt,) = _get_struct_3f3b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f3b = None
def _get_struct_3f3b():
    global _struct_3f3b
    if _struct_3f3b is None:
        _struct_3f3b = struct.Struct("<3f3b")
    return _struct_3f3b
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
