// Generated by gencpp from file ntuc_fleet/agv_status.msg
// DO NOT EDIT!


#ifndef NTUC_FLEET_MESSAGE_AGV_STATUS_H
#define NTUC_FLEET_MESSAGE_AGV_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ntuc_fleet
{
template <class ContainerAllocator>
struct agv_status_
{
  typedef agv_status_<ContainerAllocator> Type;

  agv_status_()
    : cmd(0)
    , time()
    , status(0)
    , location(0)
    , arrival()
    , b_level(0)
    , e_status(0)
    , complete(0)
    , lastLP(0)  {
    }
  agv_status_(const ContainerAllocator& _alloc)
    : cmd(0)
    , time()
    , status(0)
    , location(0)
    , arrival()
    , b_level(0)
    , e_status(0)
    , complete(0)
    , lastLP(0)  {
  (void)_alloc;
    }



   typedef int8_t _cmd_type;
  _cmd_type cmd;

   typedef ros::Time _time_type;
  _time_type time;

   typedef int8_t _status_type;
  _status_type status;

   typedef int8_t _location_type;
  _location_type location;

   typedef ros::Time _arrival_type;
  _arrival_type arrival;

   typedef int8_t _b_level_type;
  _b_level_type b_level;

   typedef int8_t _e_status_type;
  _e_status_type e_status;

   typedef int8_t _complete_type;
  _complete_type complete;

   typedef int8_t _lastLP_type;
  _lastLP_type lastLP;





  typedef boost::shared_ptr< ::ntuc_fleet::agv_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ntuc_fleet::agv_status_<ContainerAllocator> const> ConstPtr;

}; // struct agv_status_

typedef ::ntuc_fleet::agv_status_<std::allocator<void> > agv_status;

typedef boost::shared_ptr< ::ntuc_fleet::agv_status > agv_statusPtr;
typedef boost::shared_ptr< ::ntuc_fleet::agv_status const> agv_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ntuc_fleet::agv_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ntuc_fleet::agv_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ntuc_fleet

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ntuc_fleet': ['/home/rac/catkin_ws/src/ntuc_fleet/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ntuc_fleet::agv_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ntuc_fleet::agv_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ntuc_fleet::agv_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ntuc_fleet::agv_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ntuc_fleet::agv_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ntuc_fleet::agv_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ntuc_fleet::agv_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b47d165e9912a2afc0c77fd2d5b0bfa";
  }

  static const char* value(const ::ntuc_fleet::agv_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b47d165e9912a2aULL;
  static const uint64_t static_value2 = 0xfc0c77fd2d5b0bfaULL;
};

template<class ContainerAllocator>
struct DataType< ::ntuc_fleet::agv_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ntuc_fleet/agv_status";
  }

  static const char* value(const ::ntuc_fleet::agv_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ntuc_fleet::agv_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "##################################################\n\
##### Message type: status.msg\n\
##### Use in Topics: /to_fleet, /to_station\n\
##################################################\n\
int8 cmd			# command code	 \n\
time time		# fleet manager current time\n\
int8 status		# AGV status\n\
int8 location		# AGV location\n\
time arrival		# estimate time of arrival\n\
int8 b_level		# battery level in %\n\
int8 e_status		# elevator status \n\
int8 complete		# task completion / ready for next task\n\
int8 lastLP			# LP when the last task has just completed\n\
\n\
##################################################\n\
## cmd		1:op_status, 2:alert, 3:alarm, 4:agv_status\n\
## time		time in time.secs and and time.nsecs \n\
## status	1:delivering food, 2:traffic jam, 3:breakdown, 4:fire alarm, 5:charging\n\
## location	0:L1Store,1:L1Laundry,2:L1NonHalal,3:L3,4:L4,5:L5,6:L6,\n\
##				7:L7,8:L8,9:L9,10:L10Dorm,11:L11,12:L1Charging\n\
## arrival	time in time.secs and and time.nsecs\n\
## b_level	percent of battery level\n\
## lift_status	1:okay, 2:service alarm, 3:fire alarm \n\
## complete	0:ready for task, 1:completed & ready, 2:completed not ready, 3:not ready, \n\
##				4:job-aborted not ready, 5:job-aborted ready\n\
## lastLP	73:L1LRm3, 74:L1LRm4, 75:L1LRm5, 76:L1LRm6, 77:L1LRm7, 78:L1LRm8, 79:L1LRm9,\n\
##				3:L3Ward3, 4:L4Ward4, 5:L5Ward5, 6:L6Ward6, 7:L7Ward7, 8:L8Ward8, 9:L9Ward,\n\
##				10: L10StaffDorm, 11:L11Ktchen,\n\
##				51:L1MainStore, 52:L1NonHalalPrepRoom\n\
##################################################	\n\
";
  }

  static const char* value(const ::ntuc_fleet::agv_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ntuc_fleet::agv_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.time);
      stream.next(m.status);
      stream.next(m.location);
      stream.next(m.arrival);
      stream.next(m.b_level);
      stream.next(m.e_status);
      stream.next(m.complete);
      stream.next(m.lastLP);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct agv_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ntuc_fleet::agv_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ntuc_fleet::agv_status_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time);
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
    s << indent << "location: ";
    Printer<int8_t>::stream(s, indent + "  ", v.location);
    s << indent << "arrival: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.arrival);
    s << indent << "b_level: ";
    Printer<int8_t>::stream(s, indent + "  ", v.b_level);
    s << indent << "e_status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.e_status);
    s << indent << "complete: ";
    Printer<int8_t>::stream(s, indent + "  ", v.complete);
    s << indent << "lastLP: ";
    Printer<int8_t>::stream(s, indent + "  ", v.lastLP);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NTUC_FLEET_MESSAGE_AGV_STATUS_H
