// Generated by gencpp from file htbot/scanMcmdRequest.msg
// DO NOT EDIT!


#ifndef HTBOT_MESSAGE_SCANMCMDREQUEST_H
#define HTBOT_MESSAGE_SCANMCMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace htbot
{
template <class ContainerAllocator>
struct scanMcmdRequest_
{
  typedef scanMcmdRequest_<ContainerAllocator> Type;

  scanMcmdRequest_()
    : cmd(0)
    , file()
    , lp(0)
    , gp(0)  {
    }
  scanMcmdRequest_(const ContainerAllocator& _alloc)
    : cmd(0)
    , file(_alloc)
    , lp(0)
    , gp(0)  {
  (void)_alloc;
    }



   typedef int8_t _cmd_type;
  _cmd_type cmd;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _file_type;
  _file_type file;

   typedef int8_t _lp_type;
  _lp_type lp;

   typedef int8_t _gp_type;
  _gp_type gp;





  typedef boost::shared_ptr< ::htbot::scanMcmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::htbot::scanMcmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct scanMcmdRequest_

typedef ::htbot::scanMcmdRequest_<std::allocator<void> > scanMcmdRequest;

typedef boost::shared_ptr< ::htbot::scanMcmdRequest > scanMcmdRequestPtr;
typedef boost::shared_ptr< ::htbot::scanMcmdRequest const> scanMcmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::htbot::scanMcmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::htbot::scanMcmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace htbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'htbot': ['/home/rac/catkin_ws/src/htbot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::htbot::scanMcmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::htbot::scanMcmdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::htbot::scanMcmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::htbot::scanMcmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::htbot::scanMcmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::htbot::scanMcmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::htbot::scanMcmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "024dc0671c4169424ec159005dc1f9d0";
  }

  static const char* value(const ::htbot::scanMcmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x024dc0671c416942ULL;
  static const uint64_t static_value2 = 0x4ec159005dc1f9d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::htbot::scanMcmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "htbot/scanMcmdRequest";
  }

  static const char* value(const ::htbot::scanMcmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::htbot::scanMcmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 cmd\n\
string file\n\
int8 lp\n\
int8 gp\n\
";
  }

  static const char* value(const ::htbot::scanMcmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::htbot::scanMcmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.file);
      stream.next(m.lp);
      stream.next(m.gp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct scanMcmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::htbot::scanMcmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::htbot::scanMcmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.file);
    s << indent << "lp: ";
    Printer<int8_t>::stream(s, indent + "  ", v.lp);
    s << indent << "gp: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HTBOT_MESSAGE_SCANMCMDREQUEST_H
