# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ntuc_fleet/agv_status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class agv_status(genpy.Message):
  _md5sum = "0b47d165e9912a2afc0c77fd2d5b0bfa"
  _type = "ntuc_fleet/agv_status"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """##################################################
##### Message type: status.msg
##### Use in Topics: /to_fleet, /to_station
##################################################
int8 cmd			# command code	 
time time		# fleet manager current time
int8 status		# AGV status
int8 location		# AGV location
time arrival		# estimate time of arrival
int8 b_level		# battery level in %
int8 e_status		# elevator status 
int8 complete		# task completion / ready for next task
int8 lastLP			# LP when the last task has just completed

##################################################
## cmd		1:op_status, 2:alert, 3:alarm, 4:agv_status
## time		time in time.secs and and time.nsecs 
## status	1:delivering food, 2:traffic jam, 3:breakdown, 4:fire alarm, 5:charging
## location	0:L1Store,1:L1Laundry,2:L1NonHalal,3:L3,4:L4,5:L5,6:L6,
##				7:L7,8:L8,9:L9,10:L10Dorm,11:L11,12:L1Charging
## arrival	time in time.secs and and time.nsecs
## b_level	percent of battery level
## lift_status	1:okay, 2:service alarm, 3:fire alarm 
## complete	0:ready for task, 1:completed & ready, 2:completed not ready, 3:not ready, 
##				4:job-aborted not ready, 5:job-aborted ready
## lastLP	73:L1LRm3, 74:L1LRm4, 75:L1LRm5, 76:L1LRm6, 77:L1LRm7, 78:L1LRm8, 79:L1LRm9,
##				3:L3Ward3, 4:L4Ward4, 5:L5Ward5, 6:L6Ward6, 7:L7Ward7, 8:L8Ward8, 9:L9Ward,
##				10: L10StaffDorm, 11:L11Ktchen,
##				51:L1MainStore, 52:L1NonHalalPrepRoom
##################################################	
"""
  __slots__ = ['cmd','time','status','location','arrival','b_level','e_status','complete','lastLP']
  _slot_types = ['int8','time','int8','int8','time','int8','int8','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cmd,time,status,location,arrival,b_level,e_status,complete,lastLP

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(agv_status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cmd is None:
        self.cmd = 0
      if self.time is None:
        self.time = genpy.Time()
      if self.status is None:
        self.status = 0
      if self.location is None:
        self.location = 0
      if self.arrival is None:
        self.arrival = genpy.Time()
      if self.b_level is None:
        self.b_level = 0
      if self.e_status is None:
        self.e_status = 0
      if self.complete is None:
        self.complete = 0
      if self.lastLP is None:
        self.lastLP = 0
    else:
      self.cmd = 0
      self.time = genpy.Time()
      self.status = 0
      self.location = 0
      self.arrival = genpy.Time()
      self.b_level = 0
      self.e_status = 0
      self.complete = 0
      self.lastLP = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_b2I2b2I4b().pack(_x.cmd, _x.time.secs, _x.time.nsecs, _x.status, _x.location, _x.arrival.secs, _x.arrival.nsecs, _x.b_level, _x.e_status, _x.complete, _x.lastLP))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.time is None:
        self.time = genpy.Time()
      if self.arrival is None:
        self.arrival = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 23
      (_x.cmd, _x.time.secs, _x.time.nsecs, _x.status, _x.location, _x.arrival.secs, _x.arrival.nsecs, _x.b_level, _x.e_status, _x.complete, _x.lastLP,) = _get_struct_b2I2b2I4b().unpack(str[start:end])
      self.time.canon()
      self.arrival.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_b2I2b2I4b().pack(_x.cmd, _x.time.secs, _x.time.nsecs, _x.status, _x.location, _x.arrival.secs, _x.arrival.nsecs, _x.b_level, _x.e_status, _x.complete, _x.lastLP))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.time is None:
        self.time = genpy.Time()
      if self.arrival is None:
        self.arrival = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 23
      (_x.cmd, _x.time.secs, _x.time.nsecs, _x.status, _x.location, _x.arrival.secs, _x.arrival.nsecs, _x.b_level, _x.e_status, _x.complete, _x.lastLP,) = _get_struct_b2I2b2I4b().unpack(str[start:end])
      self.time.canon()
      self.arrival.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b2I2b2I4b = None
def _get_struct_b2I2b2I4b():
    global _struct_b2I2b2I4b
    if _struct_b2I2b2I4b is None:
        _struct_b2I2b2I4b = struct.Struct("<b2I2b2I4b")
    return _struct_b2I2b2I4b
