obstacle_range: 3.0 #2.5
raytrace_range: 3.5 #3.0
max_obstacle_height: 3.0
#
# Date : 7.5.21 10.35 am
#
#footprint: [[-0.46,0.46], [-0.46,-0.46], [0.46,-0.46], [0.55,-0.09], [0.55,0.09], [0.46,0.46]]
#footprint: [[-0.4,0.4], [-0.4,-0.4], [0.4,-0.4], [0.49,-0.09], [0.49,0.09], [0.4,0.4]]
#footprint: [[-0.35,0.35], [-0.35,-0.35], [0.35,-0.35], [0.44,-0.09], [0.44,0.09], [0.35,0.35]]
#footprint: [[-0.33,0.33], [-0.33,-0.33], [0.33,-0.33], [0.42,-0.09], [0.42,0.09], [0.33,0.33]]
#footprint: [[-0.28,0.28], [-0.28,-0.28], [0.28,-0.28], [0.37,-0.09], [0.37,0.09], [0.28,0.28]]
#footprint: [[-0.26,0.26], [-0.26,-0.26], [0.34,-0.26], [0.34,0.26]]
#footprint: [[-0.3,0.3], [-0.3,-0.3], [0.3,-0.3], [0.39,-0.09], [0.39,0.09], [0.3,0.3]]
#footprint: [[-0.355,0.3],[-0.44,0.215],[-0.44,-0.215],[-0.355,-0.3],[0.355,-0.3],[0.44,-0.215], [0.44,0.215],[0.355,0.3]]
#footprint: [[-0.07,0.37],[-0.355,0.3],[-0.44,0.215],[-0.44,-0.215],[-0.355,-0.3],[-0.07,-0.37],[0.07,-0.37],[0.355,-0.3],[0.44,-0.215], [0.44,0.215],[0.355,0.3],[0.07,0.37]]
footprint: [[-0.55,0.35], [-0.55,-0.35], [0.55,-0.35], [0.55,0.35]]
#footprint: [[-0.6,0.4], [-0.6,-0.4], [0.6,-0.4], [0.6,0.4]]
#robot_radius: 0.3  #0.33
footprint_padding: 0.05
#mark_threshold: 0
cost_scaling_factor: 15.0 #15.0

inflation_radius:  0.48 #0.725 #0.49 #0.75 #0.43 #0.42 #0.51 #0.40 #0.47 #0.50 #0.75 #30.0 #6.0 #5.0#2.0 #2.5  # no cost function applied outside this radius

#observation_sources: laser_scan_sensor

#observation_sources: main_laser rplidar_left rplidar_right
#observation_sources: main_laser top_laser
#observation_sources: main_laser left_laser right_laser mapobs_laser
#observation_sources: main_laser  mapobs_laser depth_laser
#observation_sources: main_laser laser3D bottomRS_laser middleRS_laser rightRS_laser leftRS_laser #mapobs_laser
observation_sources: main_laser mapobs_laser
#observation_sources: main_laser rear_laser mapobs_laser left_laser right_laser

main_laser: {data_type: LaserScan, topic: /scanFB, marking: true, clearing: true}
rear_laser: {data_type: LaserScan, topic: /scanRR, marking: true, clearing: true}
left_laser: {data_type: LaserScan, topic: /scanLt, marking: true, clearing: true}
right_laser: {data_type: LaserScan, topic: /scanRt, marking: true, clearing: true}
bottomRSL_laser: {data_type: LaserScan, topic: /bottomScan, marking: true, clearing: true}
bottomRSR_laser: {data_type: LaserScan, topic: /bottomRScan, marking: true, clearing: true}
middleRS_laser: {data_type: LaserScan, topic: /middleScan, marking: true, clearing: true}
mapobs_laser: {data_type: LaserScan, topic: /mapscan, marking: true, clearing: true}
laser3D: {data_type: LaserScan, topic: /RoboScan, marking: true, clearing: true}
uRF: {data_type: LaserScan, topic: /ultraRF, marking: true, clearing: true}
uLF: {data_type: LaserScan, topic: /ultraLF, marking: true, clearing: true}
uFR: {data_type: LaserScan, topic: /ultraFR, marking: true, clearing: true}

#left_laser: {data_type: LaserScan, topic: /LeftScan, observation_persistence: 2.0, expected_update_rate: 1.5, marking: true, clearing: true}
#right_laser: {data_type: LaserScan, topic: /RightScan, observation_persistence: 2.0, expected_update_rate: 1.5, marking: true, clearing: true}

#laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

rplidar_left: {data_type: LaserScan, topic: /scan_rplidarL, observation_persistence: 1.0, expected_update_rate: 1.5, marking: true, clearing: true}

rplidar_right: {data_type: LaserScan, topic: /scan_rplidarR, observation_persistence: 1.0, expected_update_rate: 1.5, marking: true, clearing: true}

obstacle_layer: {enabled: true, lethal_cost_threshold: 100, track_unknown_space: true, unknown_cost_value: 255}
