obstacle_range: 2.5 #2.5
raytrace_range: 3.0 #3.0
max_obstacle_height: 3.0

#footprint: [[-0.28,0.28], [-0.28,-0.28], [0.28,-0.28], [0.37,-0.07], [0.37,0.07], [0.28,0.28]]
#footprint: [[-0.26,0.26], [-0.26,-0.26], [0.26,-0.26], [0.35,-0.05], [0.35,0.05], [0.26,0.26]]
#footprint: [[-0.255,0.255], [-0.255,-0.255], [0.344,-0.255], [0.344,0.255]]
#footprint: [[-0.3,0.0], [-0.2,0.3], [0.2,0.3], [0.3,0.0], [0.2,-0.3], [-0.2,-0.3]]
robot_radius: 0.38  #0.33
footprint_padding: 0.03
#mark_threshold: 0
cost_scaling_factor: 15.0

inflation_radius: 0.45 #30.0 #6.0 #5.0#2.0 #2.5  # no cost function applied outside this radius

#observation_sources: laser_scan_sensor

#observation_sources: main_laser rplidar_left rplidar_right
#observation_sources: main_laser top_laser
observation_sources: main_laser left_laser right_laser map_laser

main_laser: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
left_laser: {data_type: LaserScan, topic: /LeftScan, marking: true, clearing: true, observation_persistence: 2.0}
right_laser: {data_type: LaserScan, topic: /RightScan, marking: true, clearing: true, observation_persistence: 2.0}
top_laser: {data_type: LaserScan, topic: /TopScan, marking: true, clearing: true, observation_persistence: 2.0}
map_laser: {data_type: LaserScan, topic: /mapscan, marking: true, clearing: true}

#left_laser: {data_type: LaserScan, topic: /LeftScan, observation_persistence: 2.0, expected_update_rate: 1.5, marking: true, clearing: true}
#right_laser: {data_type: LaserScan, topic: /RightScan, observation_persistence: 2.0, expected_update_rate: 1.5, marking: true, clearing: true}

#laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

rplidar_left: {data_type: LaserScan, topic: /scan_rplidarL, observation_persistence: 1.0, expected_update_rate: 1.5, marking: true, clearing: true}

rplidar_right: {data_type: LaserScan, topic: /scan_rplidarR, observation_persistence: 1.0, expected_update_rate: 1.5, marking: true, clearing: true}

obstacle_layer: {enabled: true, lethal_cost_threshold: 100, track_unknown_space: true, unknown_cost_value: 255}
