# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from htbot/ultraSS.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ultraSS(genpy.Message):
  _md5sum = "9863d3f832b0ad0ccba6621fbb52a2e5"
  _type = "htbot/ultraSS"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 uFR
float32 uFL
float32 uRF
float32 uRR
float32 uLF
float32 uLR
"""
  __slots__ = ['uFR','uFL','uRF','uRR','uLF','uLR']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       uFR,uFL,uRF,uRR,uLF,uLR

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ultraSS, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.uFR is None:
        self.uFR = 0.
      if self.uFL is None:
        self.uFL = 0.
      if self.uRF is None:
        self.uRF = 0.
      if self.uRR is None:
        self.uRR = 0.
      if self.uLF is None:
        self.uLF = 0.
      if self.uLR is None:
        self.uLR = 0.
    else:
      self.uFR = 0.
      self.uFL = 0.
      self.uRF = 0.
      self.uRR = 0.
      self.uLF = 0.
      self.uLR = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.uFR, _x.uFL, _x.uRF, _x.uRR, _x.uLF, _x.uLR))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.uFR, _x.uFL, _x.uRF, _x.uRR, _x.uLF, _x.uLR,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.uFR, _x.uFL, _x.uRF, _x.uRR, _x.uLF, _x.uLR))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.uFR, _x.uFL, _x.uRF, _x.uRR, _x.uLF, _x.uLR,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
