global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 10.0 #4.0
   publish_frequency: 1.0 #5.0
   static_map: true
   transform_tolerance: 5.0 #0.5
   unknown_cost_value: 255
