controller_frequency: 14.0
recovery_behaviors: [{name: rotate_recovery, type: rotate_recovery/RotateRecovery}]
planner_patience: 10.0
controller_patience: 10.0
#base_global_planner: carrot_planner/CarrotPlanner # navfn/NavfnROS

TrajectoryPlannerROS:
# Robot Configuration Parameters
  max_vel_x: 0.65
  min_vel_x: 0.1
  escape_vel: -0.1
  max_rotational_vel: 0.4
  min_in_place_rotational_vel: 0.3
  
  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  
  holonomic_robot: false

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.02
  xy_goal_tolerance: 0.05
  latch_xy_goal_tolerance: true #false

# Forward Simulation Parameters
  sim_time: 1.8
  vx_samples: 8
  vtheta_samples: 20

# Trajectory Scoring Parameters
  meter_scoring: true
  path_distance_bias: 0.6
  goal_distance_bias: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: true
#  publish_cost_grid_pc: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05
